name: Sync to S3

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check_and_create:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials (Admin)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  # Admin credentials
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # Admin credentials
          aws-region: ${{ vars.AWS_REGION }}

      - name: Check bucket existence
        id: check
        run: |
          if aws s3api head-bucket --bucket ${{ secrets.S3_BUCKET_NAME }} 2>/dev/null; then
            echo "✓ Bucket already exists"
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "✕ Bucket does not exist, creating..."
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install boto3 pyyaml

      - name: Create S3 bucket (if not exists)
        if: steps.check.outputs.exists == 'false'
        run: |
          python $GITHUB_FOLDER_PATH/create_bucket.py
        env:
          BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          AWS_REGION: ${{ vars.AWS_REGION }}
          S3_USER: ${{ secrets.S3_USER }}

  sync_files:
    needs: [check_and_create]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials (S3_USER)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.S3_USER_ACCESS_KEY_ID }}  # S3 user credentials
          aws-secret-access-key: ${{ secrets.S3_USER_SECRET_ACCESS_KEY }}  # S3 user credentials
          aws-region: ${{ vars.AWS_REGION }}

      - name: Sync files to S3
        run: |
          aws s3 sync . s3://${{ secrets.S3_BUCKET_NAME }} \
            --exclude ".git/*" \
            --exclude ".github/*" \
            --exclude "README.md"
